# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    volumes:
      - ./migrations:/goose/migrations

volumes:
  db_data:
