# Use postgres/example user/password credentials
version: "3.9"

services:
  dev_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  # cloud_sql_proxy:
  #   image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.9.0-alpine
  #   command: ./cloud-sql-proxy study-and-learn-400500:us-central1:study-and-learn-db --credentials-file /config/application_default_credentials.json --address 0.0.0.0 --port 5432 --private-ip --run-connection-test
  #   ports:
  #     - 5434:5432
  #   volumes:
  #     - /home/lincolnjpg/.config/gcloud/application_default_credentials.json:/config/application_default_credentials.json

volumes:
  dev_db_data:
  test_db_data:
