package gqlgen

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
)

func (r *queryResolver) GetAssetIndexByID(ctx context.Context) (*User, error) {
	panic(fmt.Errorf("not implemented: GetAssetIndexByID - getAssetIndexById"))
}

func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
